### PR TITLE
Prevent XSS in requests

### PR DESCRIPTION
**Pull request by esase**
Related to skalfa/workflow#54

### CODE REVIEW

**Comment by esase** [comment]
Examles of protection: 

// raw: /oxwall_repo/groups/invitation?g/"><script>alert('s')</script>
// processed: /oxwall_repo/groups/invitationg%2F%22%3E%3Cscript%3Ealert%28%27s%27%29%3C%2Fscript%3E=

//raw: /oxwall_repo/groups/invitation/"><script>alert('s')</script>
// processed: /oxwall_repo/groups/invitation/%22%3E%3Cscript%3Ealert%28%27s%27%29%3C/script%3E

//raw: /oxwall_repo/groups/invitation/"><script>alert('s')</script>
// processed: /oxwall_repo/groups/invitation/%22%3E%3Cscript%3Ealert%28%27s%27%29%3C/script%3E

// raw: /oxwall_repo/groups/invitation?test=aa&h=/"><script>alert('s')</script>
// processed: /oxwall_repo/groups/invitationtest=aa&h=%2F%22%3E%3Cscript%3Ealert%28%27s%27%29%3C%2Fscript%3E

**Comment by esase** [comment]
Examples: 
// raw: /oxwall_repo/groups/invitation?g/&quot;&gt;&lt;script&gt;alert('s')&lt;/script&gt;
// processed: /oxwall_repo/groups/invitationg%2F%22%3E%3Cscript%3Ealert%28%27s%27%29%3C%2Fscript%3E=

//raw: /oxwall_repo/groups/invitation/&quot;&gt;&lt;script&gt;alert('s')&lt;/script&gt;
// processed: /oxwall_repo/groups/invitation/%22%3E%3Cscript%3Ealert%28%27s%27%29%3C/script%3E

//raw: /oxwall_repo/groups/invitation/&quot;&gt;&lt;script&gt;alert('s')&lt;/script&gt;
// processed: /oxwall_repo/groups/invitation/%22%3E%3Cscript%3Ealert%28%27s%27%29%3C/script%3E

// raw: /oxwall_repo/groups/invitation?test=aa&amp;h=/&quot;&gt;&lt;script&gt;alert('s')&lt;/script&gt;
// processed: /oxwall_repo/groups/invitationtest=aa&amp;h=%2F%22%3E%3Cscript%3Ealert%28%27s%27%29%3C%2Fscript%3E

**Comment by comst** [comment]
Метод работает отлично, нужно просто его переименовать в secureUrl и завести смарти модификатор для шаблонов.

**Comment by comst** [comment]
Method "secureUrl" doesn't work with URL properly (truncates servername). Need to fix it adding 2 separate methods - "secureUrl" & "secureUri".

**Pull request merged**
