### PR TITLE
Update ow.js

### PR DESCRIPTION
**Pull request by Oviglo**
In detectLink function, adding encodeURI for fix special char like \' bug.

### CODE REVIEW

**Comment by esase** [comment]
Hello could you provide to us with an example that demonstrates wrong encoding ?

**Comment by Oviglo** [comment]
OK, this web page don't work:
http://curie.fr/actualites/cancer-sein-l'interet-trastuzumab-nouvelle-fois-demontre-006882

**Comment by esase** [comment]
I have inserted your link http://curie.fr/actualites/cancer-sein-l'interet-trastuzumab-nouvelle-fois-demontre-006882 in the newsfeed on our demo. And it parsed well, Could your provide more detailed explanation ?

**Comment by Oviglo** [comment]
Yes but there are no preview

**Comment by esase** [comment]
You page gets 404 error and there is no any content

**Comment by Oviglo** [comment]
Sorry this is the good link

http://curie.fr/actualites/cancer-sein-l’interet-trastuzumab-nouvelle-fois-demontre-006882

**Comment by esase** [comment]
I have tried again and your link woks well, you can test it by you self here - http://demo.oxwall.org/

Insert your link in newsfeed

**Comment by Oviglo** [comment]
https://www.youtube.com/watch?v=Y4TSKBKJFDE&feature=youtu.be

I made a video to show my problem.

**Comment by esase** [comment]
We have added a ticket about your trouble. Thanks for the report

**Pull request closed without merging**
